spring:
  datasource:
    url: ${DIVELOG_DB_URL:jdbc:h2:/var/divelog/database/divelog}
    driver-class-name: ${DIVELOG_DB_DRIVER_CLASS_NAME:org.h2.Driver}
    username: ${DIVELOG_DB_USERNAME:sa}
    password: ${DIVELOG_DB_PASSWORD:}
  flyway:
    encoding: UTF-8
    locations:
      - "classpath:db/migration/"
    validate-on-migrate: false
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: ${DIVELOG_DB_HIBERNATE_DIALECT:org.hibernate.dialect.H2Dialect}
        hbm2ddl:
          auto: update
        jdbc:
          time_zone: "UTC"
        show_sql: ${DIVELOG_DB_SHOW_SQL:false}
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
  servlet:
    multipart:
      max-file-size: 5MB
  devtools:
    livereload:
      enabled: false

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    contextPath: ${DIVELOG_SERVLET_CONTEXT_PATH:/divelog}
    session:
      cookie:
        name: divelog-session
  tomcat:
    remoteip:
      host-header: x-forwarded-for
      protocol-header: x-forwarded-proto

divelog:
  api:
    places:
      providers:
        google:
          apiKey: ${GOOGLE_PLACES_API_KEY:}
      enhancers:
        geonames:
          username: ${GEONAMES_USERNAME:}